### ISSUE TITLE
Socket connection for autodriving

### ISSUE THREAD

**Issue by racinmat** [umautobots/GTAVisionExport#15]
In the `VisionExport.cs`, there is socket connection to some server [here](https://github.com/umautobots/GTAVisionExport/blob/master/managed/GTAVisionExport/VisionExport.cs#L75) and apparently being used to instruct this mod [here](https://github.com/umautobots/GTAVisionExport/blob/master/managed/GTAVisionExport/VisionExport.cs#L129)
 but it is nowhere mentioned in the documentation, neither I found source code for this.
Do you plan to opensource it?
Did anyone manage to get this working with their own implementation?

**Comment by barcharcraz** [comment]
we ended up using autostarting and automatic reloading instead of the socket connection.

**Comment by racinmat** [comment]
Oh, I see. Well, I created socket client with webserver so it can be started by clicking buttons. Hope someone will find it helpful.
https://github.com/racinmat/GTAVisionExport-Server
