### ISSUE TITLE
Offset between color and depth image

### ISSUE THREAD

**Issue by Cuky88** [umautobots/GTAVisionExport#18]
Hi,
I run the managed mod to save all files directly to the drive, since I couldn't manage to run the mod with database. Taking a closer look to the images, I saw that here is a huge offset between the color and depth image. Also the very first image in the tiff file is not aligned with the other images. Did someone else notice this? What could be causing this? 

Cheers,
Selcuk

**Comment by racinmat** [comment]
I think @muaz-git struggeled with that issue too. 
I did not try that, but maybe it would help, if you are gathering these images manually, by pressing "N", to pull Script.Wait before taking screenshots.
[there](https://github.com/umautobots/GTAVisionExport/blob/master/managed/GTAVisionExport/VisionExport.cs#L255) is Script.Wait in the autonomous gathering, but it is [not in manual one](https://github.com/umautobots/GTAVisionExport/blob/master/managed/GTAVisionExport/VisionExport.cs#L613) so maybe that can be the problem.

**Comment by Cuky88** [comment]
Thanks for your support. I already tried to add wait.script() before game.pause, but that didn't really help. But I currently solved this by moving game.pause(false) down infront of [Line 669](../blob/master/managed/GTAVisionExport/VisionExport.cs#L669) and I removed the different weather conditions in the for loop. This works fine now.
