### ISSUE TITLE
module machine type 'x64' conflicts with target machine type 'x86'

### ISSUE THREAD

**Issue by yipengm** [umautobots/GTAVisionExport#38]
I use followed the instruction and get this error

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	LNK1112	module machine type 'x64' conflicts with target machine type 'x86'	GTAVisionNative	C:\Users\yipengm\Desktop\GTAVisionExport-master\GTAVisionExport\master\native\build\src\ScriptHookV.lib(ScriptHookV.dll)	

I used nuget to install MinHook

**Comment by yipengm** [comment]
Solved by changing : project property/Configuration Properties/Liner/Command Line/Additional Options to X64

**Comment by lvbu2025** [comment]
On the other hand, make sure to follow

Step 8. Choose project generator 'Visual Studio 15 2017 Win64' and keep the option 'use default native compilers'

I think now the syntax of visual studio has changed that this option became "VIsual Studio 15 2017" only. Make sure to select "x64" in the drop down box down below.
