### ISSUE TITLE
GTA V does not start (launch) with GTAVisionNative.asi 

### ISSUE THREAD

**Issue by AramDonyaee** [umautobots/GTAVisionExport#46]
I have compiled everything successfully. Unfortunately, when I put **GTAVisionNative.asi** in my main GTA V installation folder, the game does not launch at all without giving any specific error or warning [I have not forgot to put GTAVisionNative.lib in installation folder but that file is not causing any problem with launching the game].

I've also downgraded GTA V, its launcher, social club, and ScripthookV to recommended version so that couldn't be the problem.

Is there any workaround for this? Thank you very much!

**Comment by vivasvan1** [comment]
How did you fix it?
