### ISSUE TITLE
Native part generates color.raw and depth.raw with only pixels and stencil.raw totaly black

### ISSUE THREAD

**Issue by jx2k6** [umautobots/GTAVisionExport#51]
color.raw is like:
![1628572861(1)](https://user-images.githubusercontent.com/16941334/128812344-4fa44e46-4bcf-4906-96b9-6a91b5c8df01.png)
depth.raw is like:
![1628572914(1)](https://user-images.githubusercontent.com/16941334/128812406-212f64d5-c7dd-4308-ab14-ee6e7038c73f.png)
stencil.raw is pure black:
![1628573027(1)](https://user-images.githubusercontent.com/16941334/128812589-16c70f7a-a82c-4ee3-bd70-308ee48afbd2.png)

After looked up all 50 issues in discussion section, I didn't find a similar problem.
Did anyone face this issue? Could you give me a hint?

logfiles are:
[asiloader.log](https://github.com/umautobots/GTAVisionExport/files/6959147/asiloader.log)
[ScriptHookV.log](https://github.com/umautobots/GTAVisionExport/files/6959148/ScriptHookV.log)
[GTANativePlugin.log](https://github.com/umautobots/GTAVisionExport/files/6959149/GTANativePlugin.log)
Nothing seems wrong to me.

I didn't downgrade GTA or Launcher since I found it's not so easy to prevent auto-update.
I tried some suggestion on shut down some graph settings but it didn't work out.
Could anyone provide a solid graph setting for windows10 GeForce RTX 2070?
Thanks!

**Comment by lvbu2025** [comment]
Hi I am dealing with this issue at the moment. Were you able to solve it? Thanks!
