### ISSUE TITLE
on native: d3d11_4.h is missing

### ISSUE THREAD

**Issue by Cuky88** [umautobots/GTAVisionExport#6]
Hi,

I ran cmake without any problems. I have also made the settings according to your Readme file in VS17. But when I want to compile it, I receive the error, that d3d11_4.h is missing:
`Error 	C1083	Datei (Include) kann nicht geöffnet werden: "d3d11_4.h": No such file or directory	GTAVisionNative	D:\Devel\GTAVisionExport\native\src\main.cpp	4	`

I looked into to the SDK folder on Windows 10, there is only d3d11.h. Microsoft says, that on Windows 10 only d3d11_3.h exists and not d3d11_4.h, but I cannot even find d3d11_3.h. Can you please help me out?

Thanks.

**Comment by yifenghuang** [comment]
You may need to change the cmakelist.txt and disable the NAMESPACE_VERSIONING option.
(not official reply, just a suggestion)

**Comment by Cuky88** [comment]
@yifenghuang this is what I have in cmakelist.txt:
```cmake_minimum_required(VERSION 3.5)
project(GTANativePlugin)
SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake/)
#add_subdirectory(deps)
add_subdirectory(src)
```

What do I need to change here?

Thanks.

**Comment by Cuky88** [comment]
I deleted everything and did follow the Readme again, as I did before. I don't know why, but now it works!

**Comment by JiamingSuen** [comment]
FYI: Build [this](https://github.com/gongminmin/UniversalDXSDK) repo and add the include folder inside VS GTAVisionNative "Additional Include Directories".
