### ISSUE TITLE
Can not configure native project

### ISSUE THREAD

**Issue by racinmat** [umautobots/GTAVisionExport#7]
Hi, I tried to install this vision export. but I could not configure a generate the project. 
I sucesfully followed steps 1 - 7.
But when I hit "configure" button, there is no EIGEN3_INCLUDE_DIR entry. 
![image](https://user-images.githubusercontent.com/5525771/31415145-d895132a-ae21-11e7-91e1-c2e749213840.png)
Although I added this entry, it did not configure properly, so I yould not generate the project.

Versions:
Cmake: 3.10.0-rc1
Eigen3: f562a193118d

**Comment by JiamingSuen** [comment]
It's because `msbuild.exe` is not in your `PATH` environment variable. One way to resolve this is to run `cmake .. -D EIGEN3_INCLUDE_DIR=(your eigen path)` in a [Developer Command Prompt for Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs).

**Comment by skyz8421** [comment]
I add the "msbuild.exe" in my "PATH" environment variable. But I still met the same problem...

**Comment by racinmat** [comment]
I can see, thanks. I added bin directory with MSBuild.exe to `PATH` variable, but now I'm stuggling with MSBuild version. 
I figured out I don't have Visual studio 2017 installed, so correct version of MSBuild is missing on my PC. Hoing to install it now, I hope it'll work after that.

**Comment by skyz8421** [comment]
I use the command line to build the project successfully, just as @JiamingSuen said.

**Comment by racinmat** [comment]
I created pull request which should fix this my misunderstanding.
