### ISSUE TITLE
Can not compile managed plugin.

### ISSUE THREAD

**Issue by racinmat** [umautobots/GTAVisionExport#9]
Hi, 
I sucessfully managed to get the native plugin work, but now I am stuggling with the managed plugin. 
I downloaded all the nuget references
copied ScriptHookVDotNet dll files to [my GTA V directory]
copied NativeUI and VAutodrive: dll files to [my GTA V directory]/scripts
and then I referenced them in References in Visual Studio. 
And there I have few issues. 
1. There was the ScriptHookVDotNet dependency, but in the latest release of ScriptHookVDotNet, there is only ScriptHookVDotNet2.dll, no ScriptHookVDotNet.dll
2. In the WMIInformation.cs, many classes are unknown (ManagementBaseObject, ObjectQuery...). But I resolved all non-nuget references for the GTAVisionUtils and it still does not compile.
I am newbie in C#, so maybe I am missing something. 
Is there any dependency I need to add instead of these that were already there?

Thanks.

**Comment by muaz-git** [comment]
@racinmat remove ScriptHookVDotNet.dll (its outdated) from references and just use ScriptHookVDotNet2.dll 
Try using nuget version of SharpDX, SharpDX.Mathematics, AWSSDK, GDAL etc. I had similar issue I guess I tried removing the project and downloaded it from git again as well.

**Comment by racinmat** [comment]
Yes, I can see, I just had to add System.Management manually, then I was able to compile everything.
